version: '3'
services:
  web:
    image: axelmoussard/webpagesurv-app:latest
    ports:
      - "${host_port}:3000"
    links:
      - api:localhost
  api:
    image: axelmoussard/webpagesurv-api:latest
    ports:
      - "3000:3000"
