version: '2'
services:
  web:
    image: axelmoussard/webpagesurv-app:latest
    ports:
      - "${app_port}:3000"
    links:
      - api:localhost
  api:
    image: axelmoussard/webpagesurv-api:latest
    ports:
      - "3000:3000"
